name: Build YallaLudoTweak
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: ${{ github.workspace }}/theos
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make perl clang dpkg-dev wget curl unzip

      - name: Install ldid (Procursus)
        run: |
          echo "deb [trusted=yes] https://repo.procurs.us/ stable main" | sudo tee /etc/apt/sources.list.d/procursus.list
          sudo apt-get update
          sudo apt-get install -y ldid

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $THEOS

      - name: Build package
        run: |
          export THEOS=$THEOS
          export PATH=$THEOS/bin:$PATH
          make package

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: YallaLudoTweak
          path: packages/*.deb
