name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y perl clang make ldid dpkg-dev

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $THEOS

      - name: Build package
        run: |
          make package

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: packages/*.deb
